### ISSUE TITLE
 maven中央库 提示找到不

### ISSUE THREAD

**Issue by tianbymy** [marvinSpring/spring-boot-starter-calma#14]

**Comment by tianbymy** [comment]
<dependency>
            <groupId>io.github.marvinspring</groupId>
            <artifactId>spring-boot-starter-calma</artifactId>
            <version>1.0.5</version>
        </dependency>

**Comment by tianbymy** [comment]
<dependency>
            <groupId>io.github.marvinspring</groupId>
            <artifactId>spring-boot-starter-calma</artifactId>
            <version>1.0.5</version>
        </dependency>

**Comment by tianbymy** [comment]
```
   <dependency>
            <groupId>io.github.marvinspring</groupId>
            <artifactId>spring-boot-starter-calma</artifactId>
            <version>1.0.5</version>
        </dependency>
```

**Comment by marvinSpring** [comment]
> 

![image](https://github.com/marvinSpring/spring-boot-starter-calma/assets/61732476/f38052b8-338b-4a74-9f46-3f1337cdfade)

**Comment by marvinSpring** [comment]
> ```
>    <dependency>
>             <groupId>io.github.marvinspring</groupId>
>             <artifactId>spring-boot-starter-calma</artifactId>
>             <version>1.0.5</version>
>         </dependency>
> ```

<dependency>
            <groupId>io.github.marvinspring</groupId>
            <artifactId>spring-boot-starter-calma</artifactId>
            <version>1.0.5</version>
        </dependency>
用这个

**Comment by marvinSpring** [comment]
> > ```
> >    <dependency>
> >             <groupId>io.github.marvinspring</groupId>
> >             <artifactId>spring-boot-starter-calma</artifactId>
> >             <version>1.0.5</version>
> >         </dependency>
> > ```
> 
> io.github.marvinspring spring-boot-starter-calma 1.0.5 用这个


<dependency>
    <groupId>io.github.marvinspring</groupId>
    <artifactId>spring-boot-starter-calma</artifactId>
    <version>1.0.5</version>
</dependency>
