### ISSUE TITLE
配置好后，抛出异常但是没有任何反应

### ISSUE THREAD

**Issue by tianbymy** [marvinSpring/spring-boot-starter-calma#15]

**Comment by marvinSpring** [comment]
可以贴下配置和对应代码看看吗

**Comment by marvinSpring** [comment]
1.0.5有bug，把版本升级到1.0.5-RELEASE就可以了：

**Comment by marvinSpring** [comment]
> _No description provided._

<dependency>
    <groupId>io.github.marvinspring</groupId>
    <artifactId>spring-boot-starter-calma</artifactId>
    <version>1.0.5-RELEASE</version>
</dependency>

**Comment by marvinSpring** [comment]
<dependency>
    <groupId>io.github.marvinspring</groupId>
    <artifactId>spring-boot-starter-calma</artifactId>
    <version>1.0.5-RELEASE</version>
</dependency>

**Comment by marvinSpring** [comment]
`<dependency>
    <groupId>io.github.marvinspring</groupId>
    <artifactId>spring-boot-starter-calma</artifactId>
    <version>1.0.5-RELEASE</version>
</dependency>`

**Comment by marvinSpring** [comment]
![image](https://github.com/marvinSpring/spring-boot-starter-calma/assets/61732476/1a87b568-41ff-4e1a-b21a-33e7272b0f8e)

**Comment by tianbymy** [comment]
1.0.5-RELEASE 直接就OK了👍🏻👍🏻👍🏻
