### ISSUE TITLE
感觉可以增加一个过滤配置，配置不需要通知的异常类型

### ISSUE THREAD

**Issue by tianbymy** [marvinSpring/spring-boot-starter-calma#16]
比如 自定义业务异常 这一类不不需要通知的 可以过滤掉

**Comment by marvinSpring** [comment]
> 比如 自定义业务异常 这一类不不需要通知的 可以过滤掉

可以啊，我觉得这个想法很好，确实需要有一个类似于过滤器的角色在这里

**Comment by marvinSpring** [comment]
> 比如 自定义业务异常 这一类不不需要通知的 可以过滤掉

你觉得将过滤配置在注解身上还是配置在配置文件中好呢

**Comment by tianbymy** [comment]
全局默认开启 异常通知，或者注解在 application上，不需要在每个controller上面去加，正在情况下，应该都需要捕捉，只有个别的比如controller，或者 BizException之类的，这种可以加上 不通知的注解。
我个人认为配置项尽可能的少比较好，纯个人喜欢。

**Comment by marvinSpring** [comment]
> 全局默认开启 异常通知，或者注解在 application上，不需要在每个controller上面去加，正在情况下，应该都需要捕捉，只有个别的比如controller，或者 BizException之类的，这种可以加上 不通知的注解。 我个人认为配置项尽可能的少比较好，纯个人喜欢。

感谢。很中肯的idea，全局开启异常通知是指web模式下每个controller都去默认加载异常捕捉吗，我觉得是可以的，配置项确实是越少越好，spring boot的starter都是尽量精简配置，考虑下个版本优先出个不通知的注解以及可以忽略特定的Exceptption，web模式全扫描倒是有点顾虑默认是开启全扫描呢还是默认不开启呢

**Comment by marvinSpring** [comment]
> 全局默认开启 异常通知，或者注解在 application上，不需要在每个controller上面去加，正在情况下，应该都需要捕捉，只有个别的比如controller，或者 BizException之类的，这种可以加上 不通知的注解。 我个人认为配置项尽可能的少比较好，纯个人喜欢。

马上情人节了，周末可能没时间搞了，只能周内下班后搞搞了时间不是很充裕i🤣

**Comment by marvinSpring** [comment]
> 全局默认开启 异常通知，或者注解在 application上，不需要在每个controller上面去加，正在情况下，应该都需要捕捉，只有个别的比如controller，或者 BizException之类的，这种可以加上 不通知的注解。 我个人认为配置项尽可能的少比较好，纯个人喜欢。

新的1.0.6版本已经支持在web模式下默认开启异常通知，并且有指定注解标注后对应接口不被监听，加了全局的IGException继承或者在需要的地方抛出他以及他的子类将可以忽略异常。

**Comment by tianbymy** [comment]
厉害了，我抓紧体验下，哈哈

**Comment by tianbymy** [comment]
感觉非常完美了，pom 引入，配置 web 模式，自定义异常 extends IGException，就OK了，过程非常简单，但意义非常重大。

**Comment by marvinSpring** [comment]
> 感觉非常完美了，pom 引入，配置 web 模式，自定义异常 extends IGException，就OK了，过程非常简单，但意义非常重大。

😊😊
